# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-22 07:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=400, verbose_name='Текст объявления')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('rooms', models.IntegerField(default=0, verbose_name='Количество комнат')),
                ('total_area', models.IntegerField(default=0, verbose_name='Общая площадь')),
                ('living_area', models.IntegerField(default=0, verbose_name='Жилая площадь')),
                ('area', models.IntegerField(default=0, verbose_name='Жилая площадь')),
                ('kitchen_area', models.IntegerField(default=0, verbose_name='Площадь кухни')),
                ('floor', models.IntegerField(default=0, verbose_name='Этаж')),
                ('floors', models.IntegerField(default=1, verbose_name='Этажность дома')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('dt', models.DateTimeField(verbose_name='Дата окончания публикации')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
            ],
            options={
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Destrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Район')),
            ],
            options={
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип операции')),
            ],
            options={
                'verbose_name_plural': 'Тип операции',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='ad',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Destrict', verbose_name='Район'),
        ),
        migrations.AddField(
            model_name='ad',
            name='operation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='website.Operation', verbose_name='Тип операции'),
        ),
    ]
