# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170122_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='', upload_to='', verbose_name='Фото', width_field=300),
        ),
        migrations.AlterField(
            model_name='ad',
            name='area',
            field=models.IntegerField(default=0, verbose_name='Жилая площадь м.кв.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='kitchen_area',
            field=models.IntegerField(default=0, verbose_name='Площадь кухни м.кв.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='living_area',
            field=models.IntegerField(default=0, verbose_name='Жилая площадь м.кв.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена, $'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='total_area',
            field=models.IntegerField(default=0, verbose_name='Общая площадь, м.кв.'),
        ),
    ]
