# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170123_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип операции')),
            ],
            options={
                'verbose_name_plural': 'Тип операции',
            },
        ),
        migrations.AddField(
            model_name='ad',
            name='operation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='website.Operation', verbose_name='Тип операции'),
        ),
    ]
