# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20170123_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.Operation', verbose_name='Тип операции'),
        ),
    ]
