# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20170123_1730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='area',
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата окончания публикации'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='media', verbose_name='Фото', width_field=300),
        ),
        migrations.AlterField(
            model_name='ad',
            name='operation',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='website.Operation', verbose_name='Тип операции'),
        ),
    ]
