# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20170126_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='area',
            field=models.IntegerField(default=0, verbose_name='Площадь м.кв.'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='photos', verbose_name='Фото', width_field=300),
        ),
    ]
