# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170126_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='dt',
            field=models.DateTimeField(verbose_name='Дата окончания публикации'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='website/photos', verbose_name='Фото', width_field=300),
        ),
    ]
